### DISCUSSION TITLE
change title bar height

### DISCUSSION THREAD

**Discussion by Waoweens** [nextapps-de/winbox#184] [Q&A]
hi, how do i change the height of the title bar? i would like to make it smaller

i tried this:
```css
.wb-header {
	height: 20px !important;
}
```
but that just pushes everything up
![image](https://github.com/user-attachments/assets/e979b760-5841-4f0d-be82-4e2cc5252562)
