### ISSUE TITLE
Feature request: different icon for maximize and unmaximize a window

### ISSUE THREAD

**Issue by cesco69** [nextapps-de/winbox#29]
Windows has two icon for **maximize** and **unmaximize** a window

![image](https://user-images.githubusercontent.com/6096678/119139412-48affb80-ba43-11eb-9157-c932df1134ca.png)

winbox has just one icon

![image](https://user-images.githubusercontent.com/6096678/119139662-8f9df100-ba43-11eb-91c7-0c234e4f00aa.png)

why don't use two different icon?

Actually the workaround is:

```css
.winbox:not(.max) .wb-max {
  background-image: url("maximize.svg") !important;
}
```

Thanks! your lib is awersome!
