### ISSUE TITLE
Expanded control over header styles?

### ISSUE THREAD

**Issue by fzammetti** [nextapps-de/winbox#3]
Hi,

Love what you're doing here!

Not an issue per se, but any chance we could get some options, or CSS guidance, for expanded control over the header, specifically changing the color of the control buttons?  I'm trying to achieve a "modern" Material look, so the header should be white, which obviously means the title and controls need to be a dark color, black most likely.  Changing the header color is of course easy with the background option, and I can create a CSS rule to color the text black no problem, but I can't seem to do the same with the controls.  I tried messing around with masks, but the results were not good.

I see that you're doing some things with themes, so maybe you're already thinking along these lines, just figured I'd ask.

Thanks and keep up the great work!
Frank

**Comment by ts-thomas** [comment]
Hi, you can achieve this by:

1. CSS only

```css
.winbox {
    background: #fff;
}
.wb-title {
    color: #000;
}
.wb-icon {
    filter: invert(1);
}
```

2. Using your own custom icons

```css
.winbox {
    background: #fff;
}
.wb-title {
    color: #000;
}
.wb-max {
    background-image: url(max-black.png);
    background-position: center center;
    background-size: 15px auto;
}
.wb-min   { /* styles */ }
.wb-full    { /* styles */ }
.wb-close { /* styles */ }
```

Would be nice if you can share your final theme(s) here, I'm looking forward.
