### ISSUE TITLE
Feature request: `no-resize` option

### ISSUE THREAD

**Issue by mossaiby** [nextapps-de/winbox#97]
A `no-resize` option would very useful, in addition to `no-max`.

Thanks.

**Comment by kodie** [comment]
You can accomplish this with CSS:

```css
/* north */
.wb-n  { display: none }

/* east */
.wb-e  { display: none }

/* south */
.wb-s  { display: none }

/* west */
.wb-w  { display: none }

/* north-west */
.wb-nw { display: none }

/* north-east */
.wb-ne { display: none }

/* south-west */
.wb-sw { display: none }

/* south-east */
.wb-se { display: none }
```
