### ISSUE TITLE
The library doesn't work without undocumented CSS

### ISSUE THREAD

**Issue by jcubic** [nextapps-de/winbox#99]
I just found after adding comment to #72

That you need to have:

```css
html, body {
    height: 100%;
}
```

If you will add winBox modal to body. Otherwise it will not work. This should be documented, because otherwise it looks like the library is broken.
